/*  Zentrust Widget – Venue Themes  */
window.ZT_THEMES = {
  grand_manor: {
    venue_id:    "grand_manor",
    venue:       "The Grand Manor",
    greet:       "Hi! I'm Ava, your AI concierge for The Grand Manor. \ud83d\udc4b\n\nI can help you browse packages, pricing & menus \u2014 or book your tour instantly with real-time availability.",
    accent:      "8E7CA5",
    accentHover: "a08db8",
    mode:        "light",
    bg:          "faf8f6",
    surface:     "ffffff",
    headerBg:    "8E7CA5",
    text:        "3d3d3d",
    textSec:     "888888",
    toggleLabel: "Check Availability",
    bookingLabel: "Tour",
    entityLabel:  "venue",
    tourHoursLabel: "Tue\u2013Thu \u00b7 8 AM \u2013 4 PM",
    tourStartHour: 8,
    tourEndHour:   17,
    tourDays:      "2,3,4",
    tourSlotInterval: 60
  },
  renaissance_catering: {
    venue_id:    "renaissance_catering",
    venue:       "Renaissance Catering",
    greet:       "Hi! I'm Ava, your AI concierge for Renaissance Catering. \ud83d\udc4b\n\nI can help you browse menus, packages & pricing \u2014 or book your tasting instantly with real-time availability.",
    accent:      "c9a84c",
    accentHover: "d4b95e",
    mode:        "dark",
    toggleLabel: "Book a Tasting",
    bookingLabel: "Tasting",
    entityLabel:  "catering",
    tourHoursLabel: "Wed \u00b7 5 PM \u2013 8 PM",
    tourStartHour: 17,
    tourEndHour:   20,
    tourDays:      "3",
    tourSlotInterval: 30,
    minLeadDays: 7
  },
  zentrust: {
    venue_id:    "",
    venue:       "Zentrust AI",
    greet:       "Hi! I'm Ava. Want to see how our AI concierge works? Ask me anything!",
    accent:      "3a9fb0",
    accentHover: "4dbbc9",
    mode:        "dark",
    toggleLabel: "Chat with Zeni",
    bookingLabel: "Tour",
    entityLabel:  "venue",
    tourHoursLabel: "Mon\u2013Fri \u00b7 9 AM \u2013 5 PM",
    tourStartHour: 9,
    tourEndHour:   17,
    tourDays:      "1,2,3,4,5"
  }
};
